### PR TITLE
Add links to Profile Page

### PR DESCRIPTION
**Pull request by ajain1921**
## Summary

Adds links to Socials/Contact section

## Changes

- Add links to profile page

## Screenshots

Screen Shot 2021-03-27 at 12 19 23 AM

### CODE REVIEW

**Review by sahithimuthyala — COMMENTED** [review]
Links look great! Only thing is I split-screen and this happened:
Screen Shot 2021-03-27 at 9 34 50 PM

Maybe we can make some CSS changes @alicesf2? Also, if you haven't pulled from main in the last 4 days, make sure you do that and resolve merge conflicts @ajain1921.

**Review by alicesf2 — APPROVED** [review]
Looks great Aditya! I think we can resolve CSS issues later (Eugenia also expressed interest in this) because I think it will require some more heavy-handed restructuring and the creation of shared class CSS files and class names.

One nit: could you make the email field a link as well? Check this out: [email links](https://www.tutorialspoint.com/html/html_email_links.htm#:~:text=HTML%20tag%20provides%20you,mailto%20instead%20of%20using%20http.&text=This%20code%20will%20generate%20the,can%20use%20to%20send%20email.)

**Review by sahithimuthyala — APPROVED** [review]

**Review by sahithimuthyala — APPROVED** [review]
💯

**Review by alicesf2 — APPROVED** [review]
💯

**Pull request merged**
